### PR TITLE
Fix: Import error sre_parse

### LINKED ISSUE #63: Import error using Python 3.11.0
I try using this library in Python 3.11.0 and I get an import error:
```
    import exrex
../../../env/lib/python3.11/site-packages/exrex.py:25: in <module>
    from re import sre_parse, U
E   ImportError: cannot import name 'sre_parse' from 're'
```

### PR DESCRIPTION
**Pull request by sumslogs**
sre_parse module was moved in py3.11.

See: python/cpython#91308

Fixes #63

### CODE REVIEW

**Comment by bac** [comment]
FWIW I've verified this change works with python 3.10 and 3.11.  I hope it can be merged and released soon as it is blocking our adoption of 3.11.

**Review by baishaohui — APPROVED** [review]
Nice change, please merge it ASAP. Thanks

**Comment by jamagalhaes** [comment]
@asciimoo can this be merged and released? thanks!

**Review by asciimoo — APPROVED** [review]
Great, thanks!
